---
title: "RNASeq_Martha"
author: "W. Evan Durno"
date: '2015-11-06'
output: html_document
---

```{r}
# Download & load EdgeR 
source("http://bioconductor.org/biocLite.R")
biocLite("edgeR")
library(edgeR)

# Download & load DESeq 
#source("http://www.bioconductor.org/biocLite.R")
#biocLite("DESeq")
library(DESeq)

# load data 
y = read.csv("y.csv",row.names=1) 
x = read.table("design.tsv") 
mve = as.character(x$slSampleType) 
ls = c( rep("S",10) , rep("L",10) ) 
strcut = function(str) substr( str , 1 , nchar(str)-1 ) 
mve = strcut(mve) 
xx = data.frame(ls,mve) 

# Conduct a test with EdgeR 
# EdgeR uses Likelihood Ratio Tests 
# We will test for effects within MVE while controlling for LS 
design = model.matrix(~ ls + mve , xx) 
dge.glm <- DGEList(y, group=xx$ls) 
dge.glm.com.disp <- estimateGLMCommonDisp(dge.glm,design, verbose=TRUE) 
dge.glm.trend.disp <- estimateGLMTrendedDisp(dge.glm.com.disp, design) 
dge.glm.tag.disp <- estimateGLMTagwiseDisp(dge.glm.trend.disp, design) 
plotBCV(dge.glm.tag.disp) 
fit <- glmFit(dge.glm.tag.disp,design) 
lrt <- glmLRT(fit,coef=grep( "mve" ,colnames(design))) 
topTags(lrt) 

# Conduct a simpler test with DESeq (not DESeq2!) 
# DESeq uses Wald tests 
ls = as.factor(ls) 
deSeqDat <- newCountDataSet(y, ls ) 
deSeqDat <- estimateSizeFactors(deSeqDat) 
deSeqDat <- estimateDispersions(deSeqDat) 
plotDispEsts(deSeqDat) 
results <- nbinomTest(deSeqDat, levels(ls)[1], levels(ls)[2]) 
plotMA(results) 
results[1:5,]
```

```{r ggplot2}
rnaseq_tbl <- read.table("y.csv", header=TRUE, sep=',')
# Melt the wide table into a tidier looking table
tidy_tbl <- melt(data = rnaseq_tbl, id.vars = "Locus.Tag")
# let's rename our columns
names(tidy_tbl) <- c("Locus.Tag", "sample", "rpkm")

#ggplot works in layers
#call gg plot, give it the data you want
# aes is aesthetics vector - what data do you want to assign to your x-axis (in this case our sample names), y axis is y variable (here take the log of her data)
# here we use a boxplot, but can call any geom plot function in there (box, scatter, etc)
scat_plot <- ggplot(tidy_tbl, aes(x=sample, y= log(x = rpkm, base=10))) +
  geom_boxplot() +
  ylab("Log_10 RPKM") +
  xlab("Samples") +
  ggtitle("Example Box Plot for Martha's data") +
  theme(axis.text.x = element_text(angle=45, hjust = 1, vjust = 1))
scat_plot



```
